---
title: "First_Script"
author: "Shamil"
date: "September 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Chunk1}
require(ggplot2)
require(lubridate)
require(maptools)
require(leaflet)
require(leaflet.esri)
require(leaflet.extras)
require(tidyverse)
require(mapview)
require(maptools)
require(htmlwidgets)
require(scales)
require(grid)
require(scales)
require(grid)
require(raster)
require(sf)
require(shiny)
require(DT)
require(crosstalk)
require(htmltools)
df <- readRDS("C:/Users/shami/Desktop/ISB research/CAPEXDX/R data/2000_cutoff/git_project_1/IUCdraft1/df.RDS")
slider <- readRDS("C:/Users/shami/Desktop/ISB research/CAPEXDX/R data/2000_cutoff/new_widget_experiments/new_widget_experiments/slider.RDS")
l2 <- filter_select("Industry","Industry", df, ~factor(Industry))
l1 <- filter_checkbox("status_type","Project Status", df, ~status_type, inline = TRUE)
l4_new <- leaflet(data=df, options = leafletOptions(preferCanvas = TRUE))%>%addTiles()%>%addCircleMarkers(color = "red", stroke = FALSE, opacity = 1)
l3 <- datatable(df, extensions="Scroller", style="bootstrap", class="compact", width="100%",options=list(deferRender=TRUE, scrollY=500, scroller=TRUE))
mapevents5 <- bscols(list(slider,l2,l1,l4_new,l3))
save_html(mapevents5,"try1.html")
```


